# ---------------------- Запуск приложений ----------------------
bindsym --to-code $mod+Return exec kitty tmux new-session
bindsym --to-code $mod+n exec kitty --title "yazi" yazi
bindsym --to-code $mod+Shift+n exec nemo

bindsym --to-code $mod+b exec TZ=UTC qutebrowser
bindsym --to-code $mod+Alt+u exec TZ=UTC qutebrowser --basedir ~/.qutebrowser/profiles/vite
bindsym --to-code $mod+Alt+i exec chromium --incognito

# Rofi (запуск программ и меню питания)
bindsym --to-code $mod+d exec rofi -combi-modi drun -font "hack 14" -show combi -show-icons
bindsym --to-code $mod+x exec rofi -show power-menu -font "hack 14" -modi power-menu:~/.config/waybar/scripts/power.sh

# --------------------- Управление окнами -----------------------
bindsym --to-code $mod+c kill
bindsym --to-code $mod+Shift+c reload
bindsym --to-code $mod+Shift+x exit

# ------------ Мультимедиа, яркость, скриншоты ------------------
bindsym --to-code --locked XF86AudioMute exec pactl set-sink-mute \@DEFAULT_SINK@ toggle
bindsym --to-code --locked XF86AudioLowerVolume exec pactl set-sink-volume \@DEFAULT_SINK@ -5%
bindsym --to-code --locked XF86AudioRaiseVolume exec pactl set-sink-volume \@DEFAULT_SINK@ +5%
bindsym --to-code --locked XF86AudioMicMute exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle

bindsym --to-code --locked XF86AudioPlay exec playerctl play-pause
bindsym --to-code --locked XF86AudioPause exec playerctl play-pause
bindsym --to-code --locked XF86AudioPrev exec playerctl previous
bindsym --to-code --locked XF86AudioNext exec playerctl next
bindsym --to-code --locked XF86AudioStop exec playerctl stop

bindsym --to-code --locked XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym --to-code --locked XF86MonBrightnessUp exec brightnessctl set 5%+

bindsym --to-code Print exec grim
