for_window [app_id="nemo"] floating enable, resize set 800 800, move position center
for_window [title=".*yazi.*"] floating enable, resize set 800 800, move position center
for_window [app_id="pavucontrol"] floating enable, resize set 800 600
