# bindsym --to-code $mod+g layout toggle tabbed split
bindsym --to-code $mod+g layout toggle tabbed split
bindsym --to-code $mod+s sticky toggle
bindsym --to-code $mod+Shift+f fullscreen toggle

# ---------- Переключение на рабочий стол по номеру ------------
#
bindsym --to-code $mod+q workspace number 1
bindsym --to-code $mod+w workspace number 2
bindsym --to-code $mod+e workspace number 3
bindsym --to-code $mod+r workspace number 4
bindsym --to-code $mod+t workspace number 5
bindsym --to-code $mod+y workspace number 6
bindsym --to-code $mod+u workspace number 7
bindsym --to-code $mod+i workspace number 8
bindsym --to-code $mod+o workspace number 9
bindsym --to-code $mod+p workspace number 10

# -------- Перемещение контейнера на рабочий стол ---------------
bindsym --to-code $mod+Shift+q move container to workspace number 1; workspace number 1
bindsym --to-code $mod+Shift+w move container to workspace number 2; workspace number 2
bindsym --to-code $mod+Shift+e move container to workspace number 3; workspace number 3
bindsym --to-code $mod+Shift+r move container to workspace number 4; workspace number 4
bindsym --to-code $mod+Shift+t move container to workspace number 5; workspace number 5
bindsym --to-code $mod+Shift+y move container to workspace number 6; workspace number 6
bindsym --to-code $mod+Shift+u move container to workspace number 7; workspace number 7
bindsym --to-code $mod+Shift+i move container to workspace number 8; workspace number 8
bindsym --to-code $mod+Shift+o move container to workspace number 9; workspace number 9
bindsym --to-code $mod+Shift+p move container to workspace number 10; workspace number 10

# --------------------- Фокус и перемещение ---------------------
# Перемещение фокуса
bindsym --to-code $mod+$left focus left
bindsym --to-code $mod+$down focus down
bindsym --to-code $mod+$up focus up
bindsym --to-code $mod+$right focus right

# Перемещение контейнера
bindsym --to-code $mod+Shift+$left move left
bindsym --to-code $mod+Shift+$down move down
bindsym --to-code $mod+Shift+$up move up
bindsym --to-code $mod+Shift+$right move right

# -------------------- Режимы и компоновка ----------------------
# Переключить плавающий режим
bindsym --to-code $mod+f floating toggle

# -------------------- Изменение размеров -----------------------
bindsym --to-code $mod+Ctrl+$left resize shrink width 10px
bindsym --to-code $mod+Ctrl+$down resize grow height 10px
bindsym --to-code $mod+Ctrl+$up resize shrink height 10px
bindsym --to-code $mod+Ctrl+$right resize grow width 10px
