set -g default-terminal "tmux-256color"

set -g allow-passthrough on
set -g terminal-features 'tmux-256color:RGB,sixel'  # Включение Sixel
set -sa terminal-overrides ",xterm*:Tc"  # Для truecolor

set -g prefix C-a
set-option -g status-position top

# Отключаем цифры (окна)
unbind 0
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9

# Перезагрузка конфига на R (Shift+r), r переезжает на окно 4
unbind r
bind R source-file ~/.tmux.conf

# change window indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @kanagawa-ignore-window-colors true

set -g status-bg black

set -g mouse on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind g set-option status
bind h split-window -h
bind s split-window

# Переключение окон буквами верхнего ряда
bind q select-window -t 1
bind w select-window -t 2
bind e select-window -t 3
bind r select-window -t 4
bind t select-window -t 5
bind y select-window -t 6
bind u select-window -t 7
bind i select-window -t 8
bind o select-window -t 9
bind p select-window -t 10
bind W choose-window
  
bind -r C-k resize-pane -U 10
bind -r C-j resize-pane -D 10
bind -r C-h resize-pane -L 10
unbind C-l
bind -r C-l resize-pane -R 10

setw -g mode-keys vi

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'Nybkox/tmux-kanagawa'

set -g @kanagawa-theme 'wave'
set -g @kanagawa-plugins "cpu-usage ram-usage"
set -g pane-border-lines 'heavy'
set -g pane-border-indicators 'both'

run '~/.tmux/plugins/tpm/tpm'
